# do not touch this line
configVersion: 2

description: An app for pass slides by gestures
keywords: 'slide, gesture'
name: slider
displayName: Slider

services:
  faceTest:
    engine: gesture
    type: palm
